#!/usr/bin/env ruby
# frozen_string_literal: true

DEBUG = ENV["UNDRIVE_DEBUG"] == "true"

# Std-lib
require "optparse"

# Gems
require "bundler/setup"
require "byebug" if DEBUG

# This library
require "undrive_google"

cli = UndriveGoogle::CLI.instance
cli.parse(ARGV)
cli.liberate!
