#!/usr/bin/env ruby
# frozen_string_literal: true

# Std-lib
require "optparse"

# Gems
require "bundler/setup"
require "byebug"

# This library
require "undrive_google"

cli = UndriveGoogle::CLI.instance
cli.parse(ARGV)
cli.liberate!
